'use client';

import { useMemo, useEffect, useState } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import Link from 'next/link';
import type { Test, Question } from '@/utils/types';
import toast from 'react-hot-toast';
import {
  HiArrowLeft,
  HiPencil,
  HiUserAdd,
  HiEye,
  HiChartBar,
  HiTrash,
  HiSparkles,
  HiX,
  HiClipboardCopy,
} from 'react-icons/hi';

const questionTypeLabel: Record<string, string> = {
  multiple_choice: 'Multiple Choice',
  true_false: 'True / False',
  open_ended: 'Open Ended',
  fill_in_blank: 'Fill in the Blank',
};

export default function TestDetailPage() {
  const { id } = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const isNewlyGenerated = searchParams.get('new') === 'true';
  const [test, setTest] = useState<Test & { material?: { title: string }; questions?: Question[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const [showBanner, setShowBanner] = useState(isNewlyGenerated);
  const supabase = useMemo(() => createClient(), []);
  const router = useRouter();

  useEffect(() => {
    const fetchTest = async () => {
      const { data, error } = await supabase
        .from('tests')
        .select('*, material:materials(title), questions(*)')
        .eq('id', id)
        .single();

      if (error || !data) {
        toast.error('Test not found');
        router.push('/teacher/tests');
      } else {
        if (data.questions) {
          data.questions.sort((a: Question, b: Question) => a.order_index - b.order_index);
        }
        setTest(data);
      }
      setLoading(false);
    };

    fetchTest();
  }, [id]);

  const togglePublish = async () => {
    if (!test) return;

    const res = await fetch(`/api/tests/${id}/publish`, { method: 'PATCH' });
    const data = await res.json();

    if (res.ok) {
      setTest({ ...test, is_published: data.test.is_published, access_code: data.test.access_code });
      toast.success(data.test.is_published ? 'Test published!' : 'Test unpublished');
    } else {
      toast.error('Failed to update');
    }
  };

  const handleDelete = async () => {
    if (!confirm('Delete this test and all its questions?')) return;

    const { error } = await supabase.from('tests').delete().eq('id', id);
    if (error) {
      toast.error('Failed to delete');
    } else {
      toast.success('Test deleted');
      router.push('/teacher/tests');
    }
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="skeleton h-8 w-64 mb-4" />
        <div className="skeleton h-4 w-96 mb-8" />
      </div>
    );
  }

  if (!test) return null;

  return (
    <div className="max-w-4xl mx-auto">
      <Link
        href="/teacher/tests"
        className="inline-flex items-center gap-1 text-text-secondary hover:text-text-primary mb-6"
      >
        <HiArrowLeft className="w-4 h-4" />
        Back to Tests
      </Link>

      {/* AI Generated Banner */}
      {showBanner && (
        <div className="card p-4 mb-6 border-2 border-primary/30 bg-gradient-to-r from-primary/10 to-accent-cyan/10">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-3">
              <HiSparkles className="w-6 h-6 text-primary flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-primary mb-1">Test Generated by AI</h3>
                <p className="text-sm text-text-secondary">
                  Your test has been automatically created from the uploaded material.
                  Review the questions below and edit as needed before publishing.
                </p>
              </div>
            </div>
            <button
              onClick={() => setShowBanner(false)}
              className="p-1 hover:bg-white/10 rounded"
            >
              <HiX className="w-5 h-5 text-text-secondary" />
            </button>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold mb-2">{test.title}</h1>
          {test.description && (
            <p className="text-text-secondary">{test.description}</p>
          )}
          <div className="flex items-center gap-3 mt-3">
            <span className={test.is_published ? 'badge-success' : 'badge-warning'}>
              {test.is_published ? 'Published' : 'Draft'}
            </span>
            <span className="text-sm text-text-secondary">
              {test.question_count} questions
            </span>
            {test.material && (
              <span className="text-sm text-text-secondary">
                From: {test.material.title}
              </span>
            )}
          </div>
        </div>

        <div className="flex gap-2">
          <button onClick={togglePublish} className="btn-secondary flex items-center gap-1 text-sm">
            <HiEye className="w-4 h-4" />
            {test.is_published ? 'Unpublish' : 'Publish'}
          </button>
          <button onClick={handleDelete} className="btn-danger flex items-center gap-1 text-sm">
            <HiTrash className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Access Code */}
      {test.access_code && (
        <div className="card p-5 mb-6 border border-accent-cyan/30 bg-accent-cyan/5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-text-secondary mb-1">Test Access Code</p>
              <p className="text-3xl font-mono font-bold tracking-widest text-accent-cyan">
                {test.access_code}
              </p>
              <p className="text-xs text-text-secondary mt-2">
                Share this code with students so they can join the test
              </p>
            </div>
            <button
              onClick={() => {
                navigator.clipboard.writeText(test.access_code!);
                toast.success('Code copied!');
              }}
              className="btn-secondary flex items-center gap-2"
            >
              <HiClipboardCopy className="w-5 h-5" />
              Copy Code
            </button>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        <Link href={`/teacher/tests/${id}/edit`} className="card-hover p-4 flex items-center gap-3">
          <HiPencil className="w-5 h-5 text-primary" />
          <span className="font-medium text-sm">Edit Questions</span>
        </Link>
        <Link href={`/teacher/tests/${id}/assign`} className="card-hover p-4 flex items-center gap-3">
          <HiUserAdd className="w-5 h-5 text-accent-cyan" />
          <span className="font-medium text-sm">Assign to Students</span>
        </Link>
        <Link href={`/teacher/tests/${id}/results`} className="card-hover p-4 flex items-center gap-3">
          <HiChartBar className="w-5 h-5 text-accent-violet" />
          <span className="font-medium text-sm">View Results</span>
        </Link>
      </div>

      {/* Questions Preview */}
      <h2 className="text-lg font-semibold mb-4">Questions</h2>
      <div className="space-y-4">
        {test.questions?.map((q, i) => (
          <div key={q.id} className="card p-5">
            <div className="flex items-start gap-3">
              <span className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center text-sm font-medium flex-shrink-0">
                {i + 1}
              </span>
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <span className="badge-primary text-xs">
                    {questionTypeLabel[q.question_type]}
                  </span>
                  <span className="text-xs text-text-secondary">
                    {q.points} {q.points === 1 ? 'point' : 'points'}
                  </span>
                </div>
                <p className="mb-3">{q.question_text}</p>

                {q.options && (
                  <div className="space-y-1 mb-3">
                    {q.options.map((opt, j) => (
                      <div
                        key={j}
                        className={`text-sm px-3 py-1.5 rounded ${
                          opt === q.correct_answer
                            ? 'bg-green-500/10 text-green-400'
                            : 'text-text-secondary'
                        }`}
                      >
                        {String.fromCharCode(65 + j)}. {opt}
                        {opt === q.correct_answer && ' (correct)'}
                      </div>
                    ))}
                  </div>
                )}

                {!q.options && (
                  <p className="text-sm text-green-400 mb-2">
                    Answer: {q.correct_answer}
                  </p>
                )}

                {q.explanation && (
                  <p className="text-xs text-text-secondary italic">
                    {q.explanation}
                  </p>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
